export const gameplayCopy = {
  dataUnavailable: 'NOT YET KNOWN',
  catchForEntry: 'Catch this Pokémon to add its Pokédex entry.',
  catchForFullData: 'Catch this Pokémon to add its full Pokédex data.',
  pokedexUnavailable: 'No Pokédex entry is available for this Pokémon.',
  noMoveSelected: 'NO MOVE SELECTED',
  selectMove: 'Select a move in battle to view its details.',
  noMovesRecorded: 'NO MOVES RECORDED',
  movesWillAppear: 'Moves used in battle will appear here.',
  moveEffectUnavailable: 'No effect description is available.',
  abilityUnavailable: 'No ability description is available.',
  moveDataUnavailable: 'MOVE LIST NOT READY',
  chooseMoveList: 'Choose a level-up list in Settings.',
  noAdditionalData: 'Nothing else has been recorded for this Pokémon.',
} as const;
