package com.enrpau.dualscreendex.parser.cli

import com.google.gson.GsonBuilder
import com.google.gson.JsonObject
import com.google.gson.JsonParser
import java.io.File
import java.nio.file.Files
import java.nio.file.Path
import java.security.MessageDigest
import java.util.concurrent.TimeUnit
import java.util.jar.JarFile
import org.junit.Assert.*

/** Generated bytes and public Gen I table-layout constants only; not official-ROM authority. */
internal object SyntheticPersistenceCliFixture {
    fun image(): ByteArray = ByteArray(0x100000).also { bytes ->
        "POKEMON RED".toByteArray(Charsets.US_ASCII).copyInto(bytes, 0x134)
        fun name(index: Int) = byteArrayOf(0x8C.toByte(), 0x8E.toByte(), 0x8D.toByte(),
            (0x80 + index / 26).toByte(), (0x80 + index % 26).toByte(), 0x50)
        repeat(190) { index ->
            bytes.fill(0x50, 0x1C21E + index * 10, 0x1C21E + (index + 1) * 10)
            name(index).copyInto(bytes, 0x1C21E + index * 10)
        }
        repeat(151) { index ->
            val offset = 0x383DE + index * 28
            bytes[offset] = (index + 1).toByte()
            repeat(5) { bytes[offset + 1 + it] = (40 + index % 50).toByte() }
            bytes[offset + 8] = 45
            bytes[offset + 9] = 64
        }
        repeat(165) { index ->
            name(index).copyInto(bytes, 0xB0000 + index * 6)
            val offset = 0x38000 + index * 6
            bytes[offset] = (index + 1).toByte()
            bytes[offset + 2] = 40
            bytes[offset + 4] = 100
            bytes[offset + 5] = 20
        }
        repeat(12) { index ->
            val offset = 0x3E474 + index * 3
            bytes[offset] = index.toByte()
            bytes[offset + 1] = ((index + 1) % 12).toByte()
            bytes[offset + 2] = 20
        }
        bytes[0x3E474 + 36] = 0xFF.toByte()
    }

    data class Capture(val directory: Path, val jars: List<Path>, val source: String,
        val fixtures: Map<String, ByteArray>, val report: JsonObject, val receipt: JsonObject) {
        val rows = report.getAsJsonArray("results").associate {
            val row = it.asJsonObject
            row["displayName"].asString to row
        }
        fun selected(): JsonObject {
            val row = rows.getValue("generated-core.gb")
            assertFalse("input failure: $row", row.has("error"))
            assertEquals("SELECTED", row.getAsJsonObject("result")["status"].asString)
            assertEquals("RED_BLUE", row.getAsJsonObject("result")["selectedFamily"].asString)
            assertFalse("materialization failure: $row", row.has("catalogError"))
            assertTrue("missing nonempty catalog: $row", row.has("catalog"))
            assertTrue(row.getAsJsonObject("catalog")["species"].asInt > 0)
            return row
        }
        fun persisted(): JsonObject {
            val row = selected()
            assertFalse("persistence failure: $row", row.has("persistenceError"))
            assertTrue("missing persistence: $row", row.has("persistence"))
            assertTrue(row.getAsJsonObject("persistence")["bytes"].asLong > 0)
            return row
        }
    }

    fun run(name: String, cache: Boolean): Capture {
        val base = System.getProperty("dualdex.test.cliEvidence")?.let(Path::of)
            ?: Files.createTempDirectory("dualdex-persistence-cli-")
        val directory = base.resolve(name)
        Files.createDirectories(directory)
        val inputs = directory.resolve("fabricated-inputs")
        Files.createDirectories(inputs)
        val fixtures = linkedMapOf("generated-core.gb" to image(), "no-catalog.gb" to ByteArray(512))
        fixtures.forEach { (file, bytes) -> Files.write(inputs.resolve(file), bytes) }
        val distribution = Path.of(requireNotNull(System.getProperty("dualdex.test.cliDistribution")))
        val jars = Files.list(distribution.resolve("lib")).use { paths ->
            paths.filter { it.fileName.toString().endsWith(".jar") }.toList()
        }
        val source = JarFile(jars.single {
            it.fileName.toString() == "parser-cli.jar" || it.fileName.toString().startsWith("parser-cli-")
        }.toFile()).use { it.manifest.mainAttributes.getValue("DualDex-Source-Commit") }
        val command = listOf(
            Path.of(System.getProperty("java.home"), "bin",
                if (System.getProperty("os.name").startsWith("Windows")) "java.exe" else "java").toString(),
            "-Xmx512m", "-Djava.io.tmpdir=${System.getProperty("java.io.tmpdir")}",
            "-cp", jars.joinToString(File.pathSeparator), "com.enrpau.dualscreendex.parser.cli.MainKt",
            inputs.toString(), "--all-roms", "--jobs", "1", "--json", directory.resolve("report.json").toString(),
            "--markdown", directory.resolve("report.md").toString(),
            "--execution-receipt", directory.resolve("receipt.json").toString(), "--source-commit", source,
        ) + if (cache) listOf("--cache-dir", directory.resolve("cache").toString()) else emptyList()
        Files.writeString(directory.resolve("command.json"), GsonBuilder().setPrettyPrinting().create().toJson(command))
        val process = ProcessBuilder(command).redirectErrorStream(true)
            .redirectOutput(directory.resolve("process.log").toFile()).start()
        try {
            assertTrue("generated CLI timed out: $directory", process.waitFor(90, TimeUnit.SECONDS))
            assertEquals("generated CLI failed: $directory", 0, process.exitValue())
        } finally {
            if (process.isAlive) { process.destroyForcibly(); process.waitFor(10, TimeUnit.SECONDS) }
        }
        return Capture(directory, jars, source, fixtures,
            JsonParser.parseString(Files.readString(directory.resolve("report.json"))).asJsonObject,
            JsonParser.parseString(Files.readString(directory.resolve("receipt.json"))).asJsonObject)
    }

    fun digest(bytes: ByteArray): String = MessageDigest.getInstance("SHA-256").digest(bytes)
        .joinToString("") { "%02x".format(it.toInt() and 255) }
}
